services:
  postgres-dev:
    image: postgres
    container_name: postgres-blogList-fso-p13-dev
    environment:
      - POSTGRES_PASSWORD=secretpassword123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data_dev:/var/lib/postgresql/data
